import { INodeProperties } from 'n8n-workflow';

export const productMgmtOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['productMgmt'],
			},
		},
		options: [
			{ name: 'Set Product', value: 'setProduct', action: 'Create or update a product' },
			{ name: 'Set Product Price', value: 'setProductPrice', action: 'Update product price' },
			{ name: 'Set Product Size', value: 'setProductSize', action: 'Update product size' },
			{ name: 'Set Product Pages', value: 'setProductPages', action: 'Update product pages' },
			{ name: 'Set Product Category', value: 'setProductCategory', action: 'Update product category' },
			{ name: 'Set Product Design', value: 'setProductDesign', action: 'Update product design links' },
			{ name: 'Set Assign Options', value: 'setAssignOptions', action: 'Assign options to product' },
			{ name: 'Set Additional Option', value: 'setAdditionalOption', action: 'Create or update a product additional option' },
			{ name: 'Set Additional Option Attributes', value: 'setAdditionalOptionAttributes', action: 'Create or update attributes for an additional option' },
			{ name: 'Set Products Attribute Price', value: 'setProductsAttributePrice', action: 'Set per-attribute pricing (with optional size range)' },
			{ name: 'Set Products Image Gallery', value: 'setProductsImageGallery', action: 'Add, update, or delete product gallery images' },
			{ name: 'Get Products Details', value: 'productsDetails', action: 'Read full product details (dedup, verify, list)' },
			{ name: 'Get Products', value: 'products', action: 'List products with basic info (id, name, sku, stock flag)' },
			{ name: 'Get Product Stocks', value: 'productStocks', action: 'Read stock entries for a product (stock_id, size_id, quantity)' },
			{ name: 'Get Product Category', value: 'productCategory', action: 'List or look up product categories (id, name, hierarchy)' },
			{ name: 'Set Product SKU', value: 'setProductSku', action: 'Register variant SKUs (per-size or per-size-option)' },
			{ name: 'Update Product Stock', value: 'updateProductStock', action: 'Add, remove, or reset stock for a variant' },
			{ name: 'Get Product SKU Matrix', value: 'getProductSkuMatrix', action: 'Read valid size and option combinations' },
			{ name: 'Get Additional Options', value: 'product_additional_options', action: 'Read product additional options' },
		],
		default: 'setProduct',
	},
];

export const productMgmtFields: INodeProperties[] = [
	// setProduct
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['productMgmt'],
				operation: ['setProduct'],
			},
		},
		default: '',
	},
	// Common Product ID for other mutations
	{
		displayName: 'Product ID',
		name: 'productId',
		type: 'number',
		required: true,
		displayOptions: {
			show: {
				resource: ['productMgmt'],
				operation: [
					'setProductPrice',
					'setProductSize',
					'setProductPages',
					'setProductCategory',
					'setProductDesign',
					'setAssignOptions',
					'setAdditionalOption',
					'setProductsImageGallery',
					'setProductSku',
					'getProductSkuMatrix',
					'productStocks',
					'product_additional_options',
				],
			},
		},
		default: 0,
	},
	// Additional Fields
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['productMgmt'],
				operation: [
					'setProduct',
					'setProductPrice',
					'setProductSize',
					'setProductPages',
					'setProductCategory',
					'setProductDesign',
					'setAssignOptions',
					'setAdditionalOption',
					'setAdditionalOptionAttributes',
					'setProductsAttributePrice',
					'setProductsImageGallery',
					'setProductSku',
					'updateProductStock',
				],
			},
		},
		options: [
			{ displayName: 'ID', name: 'id', type: 'number', default: 0 },
			{ displayName: 'SKU', name: 'sku', type: 'string', default: '' },
			{ displayName: 'Status', name: 'status', type: 'number', default: 1 },
			{ displayName: 'Description', name: 'description', type: 'string', default: '' },
			{ displayName: 'Vendor Price', name: 'vendor_price', type: 'number', default: 0 },
			{ displayName: 'Site Admin Markup', name: 'site_admin_markup', type: 'number', default: 0 },
			{ displayName: 'Size From', name: 'size_from', type: 'number', default: 0.01, description: 'Print product physical size range — leave default for apparel' },
			{ displayName: 'Size To', name: 'size_to', type: 'number', default: 99999999.99, description: 'Print product physical size range — leave default for apparel' },
			{ displayName: 'Delete', name: 'delete', type: 'number', default: 0, description: '1 to delete this row' },
			{ displayName: 'Image Gallery ID', name: 'products_image_gallery_id', type: 'number', default: 0, description: 'Existing image id — required for update/delete' },
			{ displayName: 'Corporate ID', name: 'corporate_id', type: 'number', default: 0, description: 'Override image for a specific store' },
			{ displayName: 'Image Title', name: 'title', type: 'string', default: '' },
			{ displayName: 'Option ID', name: 'option_id', type: 'number', default: 0, description: 'Bind image to a single option combination' },
			{ displayName: 'Attribute ID', name: 'attribute_id', type: 'number', default: 0, description: 'Bind image to a single attribute combination' },
			{ displayName: 'Option IDs', name: 'option_ids', type: 'string', default: '', description: 'Comma-separated option ids for multi-option bind' },
			{ displayName: 'Attribute IDs', name: 'attribute_ids', type: 'string', default: '', description: 'Comma-separated attribute ids for multi-option bind' },
			{ displayName: 'Sort Order', name: 'sort_order', type: 'number', default: 1 },
		],
	},
	// setProductsImageGallery-specific
	{
		displayName: 'Image Filename',
		name: 'imageFilename',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['productMgmt'], operation: ['setProductsImageGallery'] } },
		description: 'Filename uploaded to images/products_gallery_images on the OPS server',
		default: '',
	},
	{
		displayName: 'Optimize Image',
		name: 'optimizeImg',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['setProductsImageGallery'] } },
		description: '0 = no, 1 = yes',
		default: 0,
	},
	// setProductsAttributePrice-specific
	{
		displayName: 'Attribute ID',
		name: 'attributeId',
		type: 'number',
		required: true,
		displayOptions: { show: { resource: ['productMgmt'], operation: ['setProductsAttributePrice'] } },
		description: 'The attribute id (from setAdditionalOptionAttributes) to price',
		default: 0,
	},
	{
		displayName: 'Attributes Price',
		name: 'attributesPrice',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['setProductsAttributePrice'] } },
		default: 0,
	},
	// setAdditionalOptionAttributes-specific
	{
		displayName: 'Prod Add Opt ID',
		name: 'prodAddOptId',
		type: 'number',
		required: true,
		displayOptions: { show: { resource: ['productMgmt'], operation: ['setAdditionalOptionAttributes'] } },
		description: 'The id returned by setAdditionalOption — links this attribute to its parent option',
		default: 0,
	},
	{
		displayName: 'Label',
		name: 'label',
		type: 'string',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['setAdditionalOptionAttributes'] } },
		default: '',
	},
	// setAdditionalOption-specific fields
	{
		displayName: 'Options Type',
		name: 'optionsType',
		type: 'options',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['setAdditionalOption'] } },
		options: [
			{ name: 'Radio', value: 'radio' },
			{ name: 'Checkbox', value: 'checkbox' },
			{ name: 'Dropdown', value: 'dropdown' },
			{ name: 'Text', value: 'text' },
			{ name: 'Textarea', value: 'textarea' },
			{ name: 'Swatch', value: 'swatch' },
		],
		default: 'radio',
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['setAdditionalOption'] } },
		default: '',
	},
	// setProductSku-specific
	{
		displayName: 'SKU Type',
		name: 'skuType',
		type: 'options',
		required: true,
		displayOptions: { show: { resource: ['productMgmt'], operation: ['setProductSku'] } },
		description: 'Must match enable_stock_management on the product (1=size_wise, 2=size_option_wise)',
		options: [
			{ name: 'Size Wise', value: 'size_wise' },
			{ name: 'Size Option Wise', value: 'size_option_wise' },
		],
		default: 'size_wise',
	},
	// updateProductStock-specific
	{
		displayName: 'Action',
		name: 'action',
		type: 'options',
		required: true,
		displayOptions: { show: { resource: ['productMgmt'], operation: ['updateProductStock'] } },
		options: [
			{ name: 'Add', value: 'Add', description: 'Add to existing stock (or create the row on first call)' },
			{ name: 'Remove', value: 'Remove', description: 'Subtract from existing stock' },
			{ name: 'Reset', value: 'Reset', description: 'Overwrite to the given quantity' },
		],
		default: 'Add',
	},
	{
		displayName: 'Product SKU',
		name: 'productSku',
		type: 'string',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['updateProductStock'] } },
		description: 'Registered variant SKU from setProductSku. Use this OR Stock ID (Stock ID wins on edits).',
		default: '',
	},
	{
		displayName: 'Stock ID',
		name: 'stockId',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['updateProductStock'] } },
		description: 'Existing stock_id from productStocks query. Required for edits; omit for initial Add.',
		default: 0,
	},
	// productCategory-specific
	{
		displayName: 'Category ID',
		name: 'categoryId',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['productCategory'] } },
		description: 'Filter to a single category. Leave 0 to list.',
		default: 0,
	},
	{
		displayName: 'Limit',
		name: 'productCategoryLimit',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['productCategory'] } },
		default: 50,
	},
	{
		displayName: 'Offset',
		name: 'productCategoryOffset',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['productCategory'] } },
		default: 0,
	},
	// products-specific (light list query)
	{
		displayName: 'Products ID',
		name: 'productsListProductId',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['products'] } },
		description: 'Filter to a single product. Leave 0 to list.',
		default: 0,
	},
	{
		displayName: 'Limit',
		name: 'productsListLimit',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['products'] } },
		default: 10,
	},
	{
		displayName: 'Offset',
		name: 'productsListOffset',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['products'] } },
		default: 0,
	},
	// productsDetails-specific (read query — all filters optional)
	{
		displayName: 'Products ID',
		name: 'productsDetailsProductId',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['productsDetails'] } },
		description: 'Filter to a single product. Leave 0 to list.',
		default: 0,
	},
	{
		displayName: 'Limit',
		name: 'productsDetailsLimit',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['productsDetails'] } },
		default: 10,
	},
	{
		displayName: 'Offset',
		name: 'productsDetailsOffset',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['productsDetails'] } },
		default: 0,
	},
	{
		displayName: 'Status',
		name: 'productsDetailsStatus',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['productsDetails'] } },
		description: 'Filter by product status (0 = no filter, 1 = active)',
		default: 0,
	},
	{
		displayName: 'All Store',
		name: 'productsDetailsAllStore',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['productsDetails'] } },
		description: 'Filter by store availability',
		default: 0,
	},
	{
		displayName: 'External Catalogue',
		name: 'productsDetailsExternalCatalogue',
		type: 'number',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['productsDetails'] } },
		description: '0 or 1',
		default: 0,
	},
	// getProductSkuMatrix-specific
	{
		displayName: 'Additional Option IDs',
		name: 'prodAddOptIds',
		type: 'string',
		displayOptions: { show: { resource: ['productMgmt'], operation: ['getProductSkuMatrix'] } },
		description: 'Comma-separated. Omit for size-wise matrix; provide for size×option matrix.',
		default: '',
	},
	// Query params shared by light queries
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['productMgmt'],
				operation: ['product_additional_options', 'productStocks'],
			},
		},
		default: 10,
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['productMgmt'],
				operation: ['product_additional_options', 'productStocks'],
			},
		},
		default: 0,
	},
];
